open: {id:"juhuasuan-list-url",expire:"{date:'20190215',message:'运行异常'}",image:true,name:"聚划算链接",init:"https://ju.taobao.com",link:"input",timeout:30,threads:1,brower:"chrome",scroll:1,remark:"天猫商品的评论采集"}
   list: {xpath:"//a[@class='link-box hover-blank']",wait:10000,scroll:-1}
       text: {xpath:"",attribute:"href",name:"链接",handler:"JuUrl"}