open: {id:"tianmao-fuwu-detail",name:"天猫商品服务承诺",image:false,link:"input",timeout:30,threads:1,major:true,brower:"chrome",remark:"采集淘宝搜索列表里的普通店铺宝贝（除天猫商品）",help:"功能：淘宝关键词搜索后，采集列表的标题、地区、卖家淘宝名、宝贝链接\n1.关键词放到'采集软件'，点击'启动'，软件打开一个浏览器，自动采集数据\n2.请不要软件控制的浏览器"}
       text: {xpath:"",name:"电脑端商品链接",handler:"TaobaoPcUrl",wait:1000}
       text: {xpath:"//a[@class='slogo-shopname']/strong",name:"店铺名称"}
       text: {xpath:"//div[@class='tb-detail-hd']",name:"标题"}
       text: {xpath:"//ul[@class='tb-serPromise']",name:"服务"}
