open: {id:"tianmao-list-web-url",image:true,name:"天猫手机端列表链接",help:"天猫列表链接",init:"https://list.tmall.com/",link:"input",timeout:30,threads:1,brower:"chrome-phone",remark:"天猫商品的评论采集"}
     list: {xpath:"//a[@class='list_item']",scroll:-1}
       text: {xpath:"",attribute:"href",name:"链接"}