open: {id:"jutaobao-list-url",image:true,name:"聚划算列表转天猫链接",help:"聚划算列表转天猫链接",link:"input",timeout:30,threads:1,brower:"chrome",remark:"天猫商品的评论采集"}
     list: {xpath:"//div[@class='ju-itemlist J_JuSeekList']/ul/li/div/a",wait:10000,scroll:-1}
       text: {xpath:"",attribute:"href",name:"链接",handler:"JuTaoBaoText"}
