open: {id:"sycm.taobao.com-xpath-config",image:true,sort:true,exportall:true,name:"生意经-单条数据",init:"https://sycm.taobao.com/custom/login.htm?_target=http://sycm.taobao.com/",link:"https://sycm.taobao.com/mq/words/search_words.htm#/?dateRange=2017-12-31%7C2017-12-31&dateType=recent1&device=0&keyword=1",brower:"chrome",timeout:30,threads:1,major:true}
   click: {xpath:"//a[text()='相关搜索词']",wait:1000}
   click: {xpath:"//span[@class='dtpicker-main-text']",wait:1000}
   click: {xpath:"//div[@class='dtpicker-menu']/ul/li[2]",wait:500}
   input: {xpath:"//input[@class='main-search-input']",value:"input",keydown:true}
     click: {xpath:"//span[text()='搜索人数占比']/parent::span/span[1]",wait:1500}
     click: {xpath:"//span[text()='搜索热度']/parent::span/span[1]",wait:500}
     click: {xpath:"//span[text()='交易指数']/parent::span/span[1]",wait:500}
     click: {xpath:"//span[text()='支付转化率']/parent::span/span[1]",wait:500}
     text: {xpath:"//span[@class='keyword-value']",name:"关键词",global:true}
     list: {xpath:"//table[@class='table-ng table-ng-basic related-word-table']/tbody/tr",exclude:"target",wait:3000}
         text: {xpath:"/td[1]",name:"搜索人气",handler:"SycmText"}
         text: {xpath:"/td[1]",name:"点击率",handler:"SycmText"}
         text: {xpath:"/td[1]",name:"在线商品数",handler:"SycmText"}
         text: {xpath:"/td[1]",name:"直通车参考价",handler:"SycmText"}
         text: {xpath:"/td[1]",name:"交易指数",handler:"SycmText"}
         text: {xpath:"/td[1]",name:"支付转化率",handler:"SycmText"}
