open: {id:"taobao-jutou-wangwang",name:"聚透旺旺",image:false,link:"input",major:true,timeout:15,threads:1,brower:"chrome",remark:"https://qiang.taobao.com/category.htm?spm=a21bz.7725273.2164140.1.32003db8dSWwKP&categoryId=312000"}
      list : {xpath:"//ul/li/div/a"}
        text : {xpath:"",attribute:"href",name:"旺旺",handler:"TaojinbiText"}
        text : {xpath:"",attribute:"href",name:"商品链接",handler:"TaoBaoProductUrl"}

