open: {id:"taobao-jupage-wangwang",name:"天天特价旺旺",image:true,init:"https://jupage.taobao.com/wow/tttj/act/index",link:"",major:true,scroll:-1,timeout:15,threads:1,brower:"chrome",remark:"https://qiang.taobao.com/category.htm?spm=a21bz.7725273.2164140.1.32003db8dSWwKP&categoryId=312000"}
   page:{xpath:"//a[contains(@class,'next') and not(contains(@class,'disabled')) ]",scorll:-1}
      list : {xpath:"//div[@class='items']/a[@class='item']"}
        text : {xpath:"",attribute:"href",name:"旺旺",handler:"TaojinbiText"}

