open: {id:"taobao-ztc-new-list",labels:"转化率大于等于,提高出价,平均点击花费,过去（7或14或30）天做对比,平均展现排名升价排名临界点",image:true,name:"淘宝直通车新版升价",link:"input",timeout:15,threads:1,major:true,brower:"chrome",init:"http://zhitongche.taobao.com/",remark:"http://zhitongche.taobao.com/",help:"淘宝直通车"}
   text: {xpath:"",name:"直通车操作步骤",handler:"TaobaoZtcNewHandler"}
