open: {link:"input",id:"3e3e-list",name:"3e3e",timeout:15,threads:1,major:true,brower:"chrome",monitor:true,remark:"http://permit.mep.gov.cn/permitExt/outside/Publicity?pageno=1&enterName=&province=&city=&treadcode=&treadname=&xkznum="}
   page:{xpath:"//a[@class='pagebut'][text()='下一页']"} 
    list: {xpath:"//div[@class='product-img-box']/a",wait:2000}
      text: {xpath:"",attribute:"href",name:"链接"}
