open: {id:"adidas-list",filter:false,image:false,scroll:-1,name:"阿迪达斯列表链接",link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"http://tj.milike.com/estate/1000003.htm###"}
       list: {xpath:"//div[@class='thumbnail']/a"}
          text: {xpath:"",attribute:"href",name:"链接"}
