open: {id:"aliexpress-home-url",name:"速卖通整首页链接",image:true,link:"input",timeout:15,threads:1,brower:"chrome",remark:"https://baseus.aliexpress.com/store/group/Wireless-charger/2343184_511590492.html?spm=2114.12010612.0.0.3d3a75509kAjWS"}
    list: {xpath:"//div[@class='hover-help']/div[@class='item-title-wrap']/a",scroll:-1}
      text: {xpath:"",attribute:"href", name:"链接"}
