open: {id:"amazon-address2",filter:false ,image:true,name:"美国亚马逊地址22",link:"input",init:"https://sellercentral.amazon.com/",major:true,brower:"chrome",timeout:10,threads:1,remark:"https://www.amazon.de/"}
    list: {xpath:"//div[@class='cell-body-title']/a",wait:2000}
       text: {xpath:"",attribute:"href",name:"链接"}
