open: {link:"input",id:"ctnews-list",name:"ctnews",timeout:15,threads:1,major:true,brower:"chrome",monitor:true,remark:"http://permit.mep.gov.cn/permitExt/outside/Publicity?pageno=1&enterName=&province=&city=&treadcode=&treadname=&xkznum="}
    list: {xpath:"//div[@class='jsearch-result-title']/a"}
      text: {xpath:"",attribute:"href",name:"链接"}
