open: {id:"dingdong-list-url",init:"http://old.7dingdong.com/index.php",filter:false,image:false,name:"叮咚商品链接",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"http://old.7dingdong.com/b2b/b2bgoods?page=2"}
     list: {xpath:"//div[@class='movebig']/a",wait:2000}
       text: {xpath:"",attribute:"href",name:"链接"}
