open: {id:"dy-feigua-detail",filter:false,image:true,expire:"{date:'20190928',message:''}",name:"飞瓜博主详情",init:"https://dy.feigua.cn/Member#/Aweme",link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"https://dy.feigua.cn/Member#/Aweme"}
       text : {xpath:"",name:"链接",handler:"CommonCurrentUrl"}
       text : {xpath:"",name:"博主ID",handler:"FeiGuaIdText"}
       text : {xpath:"//div[@id='js-over-view-section']/div[1]/div[1]/div[1]",name:"7最新作品数",regex:"replace|最新作品数",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[1]/div[1]/div[2]",name:"7粉丝增量",regex:"replace|粉丝增量",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[1]/div[2]/div[1]",name:"7新增点赞",regex:"replace|新增点赞",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[1]/div[2]/div[2]",name:"7新增评论",regex:"replace|新增评论",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[1]/div[2]/div[3]",name:"7新增转发",regex:"replace|新增转发",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[2]/div/div/div/h5[contains(text(),'最新作品数')]/parent::div",handler:"DelHTMLTagHandler",attribute:"innerHTML",name:"30最新作品数",regex:"replace|最新作品数",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[2]/div/div/div/h5[contains(text(),'粉丝增量')]/parent::div",handler:"DelHTMLTagHandler",attribute:"innerHTML",name:"30粉丝增量",regex:"replace|粉丝增量",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[2]/div/div/div/h5[contains(text(),'新增点赞')]/parent::div",handler:"DelHTMLTagHandler",attribute:"innerHTML",name:"30新增点赞",regex:"replace|新增点赞",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[2]/div/div/div/h5[contains(text(),'新增评论')]/parent::div",handler:"DelHTMLTagHandler",attribute:"innerHTML",name:"30新增评论",regex:"replace|新增评论",params:""}
       text : {xpath:"//div[@id='js-over-view-section']/div[2]/div/div/div/h5[contains(text(),'新增转发')]/parent::div",handler:"DelHTMLTagHandler",attribute:"innerHTML",name:"30新增转发",regex:"replace|新增转发",params:""}
       click: {xpath:"//a[text()='粉丝分析']",wait:6000}
       text : {xpath:"//li[contains(text(),'抖音号')]/span",name:"抖音号",handler:"FeiGuaWait"}
       text : {xpath:"//div[@class='info']/ul",name:"地区",attribute:"innerHTML",handler:"FeiGuaDetailText",params:"地区"}
       text : {xpath:"//div[@class='info']/ul",attribute:"innerHTML",handler:"FeiGuaDetailText",name:"年龄",params:"年龄"}
       text : {xpath:"//div[@class='info']/ul",attribute:"innerHTML",handler:"FeiGuaDetailText",name:"性别",params:"性别"}
       text : {xpath:"//div[@class='info']/ul",attribute:"innerHTML",handler:"FeiGuaDetailText",name:"分类",params:"分类"}
       text : {xpath:"//div[contains(text(),'简介')]/span",name:"简介"}
       text : {xpath:"//div[@class='rank-show']",name:"排行榜"}
       text : {xpath:"//a[contains(text(),'粉丝数')]/parent::div/span",name:"粉丝数"}
       text : {xpath:"//div[contains(text(),'作品数')]/span",name:"作品数"}
       text : {xpath:"//div[contains(text(),'总点赞')]/span",name:"总点赞"}
       text : {xpath:"//div[contains(text(),'平均点赞')]/span",name:"平均点赞"}
       text : {xpath:"//div[contains(text(),'集均评论')]/span",name:"集均评论"}
       text : {xpath:"//div[contains(text(),'集均分享')]/span",name:"集均分享"}
       text : {xpath:"//div[@class='row gender-text']/div[1]",regex:"replace|男",params:"",name:"男分布"}
       text : {xpath:"//div[@class='row gender-text']/div[2]",regex:"replace|女",params:"",name:"女分布"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[1]/td[1]",name:"地域1"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[1]/td[2]",name:"地域1占比"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[2]/td[1]",name:"地域2"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[2]/td[2]",name:"地域2占比"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[3]/td[1]",name:"地域3"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[3]/td[2]",name:"地域3占比"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[4]/td[1]",name:"地域4"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[4]/td[2]",name:"地域4占比"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[5]/td[1]",name:"地域5"}
       text : {xpath:"//table[@class='location-table']/tbody/tr[5]/td[2]",name:"地域5占比"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[1]/td[1]",attribute:"innerHTML",,name:"城市1"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[1]/td[2]",attribute:"innerHTML",,name:"城市1占比"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[2]/td[1]",attribute:"innerHTML",,name:"城市2"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[2]/td[2]",attribute:"innerHTML",,name:"城市2占比"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[3]/td[1]",attribute:"innerHTML",,name:"城市3"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[3]/td[2]",attribute:"innerHTML",,name:"城市3占比"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[4]/td[1]",attribute:"innerHTML",,name:"城市4"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[4]/td[2]",attribute:"innerHTML",,name:"城市4占比"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[5]/td[1]",attribute:"innerHTML",,name:"城市5"}
       text : {xpath:"//div[@class='section-content']/table[2]/tbody/tr[5]/td[2]",attribute:"innerHTML",,name:"城市5占比"}
       text : {xpath:"//div[@class='section-content']/ul/li[1]/div[1]",name:"星座1"}
       text : {xpath:"//div[@class='section-content']/ul/li[1]/div[3]",name:"星座1占比"}
       text : {xpath:"//div[@class='section-content']/ul/li[2]/div[1]",name:"星座2"}
       text : {xpath:"//div[@class='section-content']/ul/li[2]/div[3]",name:"星座2占比"}
       text : {xpath:"//div[@class='section-content']/ul/li[3]/div[1]",name:"星座3"}
       text : {xpath:"//div[@class='section-content']/ul/li[3]/div[3]",name:"星座3占比"}
