open: {id:"houzz-detail",filter:false,urlhandler:"HouzzDetailUrl",image:false,name:"楼梯大图",link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"https://www.houzz.com/photos/straight-staircase-ideas-phbr1-bp~t_745~a_13-453"}
       text: {xpath:"",  filename:true,name:"名字"}
       text: {xpath:"",download:true,name:"下载图片"}