open: {id:"ilikejade-url",filter:false,image:false,name:"石器链接",scroll:-1,link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"http://www.ilikejade.com/Mobile/Index/info.html?year=0&keyword="}
    list: {xpath:"//ul[@class='list_box list-unstyled']/li"}
       text: {xpath:"/div/a",name:"链接",attribute:"href"}
