open: {id:"kitbag-detail",filter:false,image:false,name:"kitbag商品图片",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"http://www.kitbag.com/stores/kitbag/en/c/football/football-boots/adidas-football-boots/adidas-predator"}
     list: {xpath:"//browse-product/a"}
       text: {xpath:"",attribute:"href",name:"链接"}
