open: {id:"milike-list",filter:false,image:false,name:"寻房链接",link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"http://www.youlu.net/shop/293993/0-1.html"}
    list: {xpath:"//div[@class='b-titlebox']/a"}
       text: {xpath:"",attribute:"href",name:"链接"}
