open: {id:"miniaturesweethk-list-main",exists:"//h5[@class='product-name']/a",filter:false,image:false,name:"miniaturesweethk列表商品链接",link:"input",major:true,brower:"chrome",timeout:10,threads:1,remark:"https://www.miniaturesweethk.com/collections/modelling-clays"}
   list: {xpath:"//h5[@class='product-name']/a"}
       text: {xpath:"",attribute:"href",name:"商品链接"}
