open: {id:"sct-term-zj-fuzhou-chinamobile",image:true,name:"福州移动终端",link:"http://term.zj.chinamobile.com/business?service=page/singleSales&_pid=4&_cid=7&_tid=2",major:true,init:"http://term.zj.chinamobile.com/business?service=page/singleSales&_pid=4&_cid=7&_tid=2",timeout:15,threads:1,brower:"chrome",remark:"http://term.chnl.zj.chinamobile.com/; http://sct.term.zj.chinamobile.com/business?service=page/singleSales&_pid=4&_cid=7&_tid=2"}
   input: {xpath:"//input[@id='enterTelTxt']",value:"input",wait:1000}
      text: {xpath:"//input[@id='enterTelTxt']",attribute:"value", name:"电话",wait:2000}
      text: {xpath:"//h3[contains(text(),'4G飞悦套餐')]/following-sibling::p",name:"4G飞悦套餐时间",handler:"TermChinamobile"}
      text: {xpath:"//h3[contains(text(),'4G飞享套餐')]/following-sibling::p",name:"4G飞享套餐时间",handler:"TermChinamobile"}
      text: {xpath:"//h3[contains(text(),'新入网')]",name:"新入网",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'新入网')]",name:"新入网时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'2018中高端_零预存')]",name:"2018中高端_零预存",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'2018中高端_零预存')]",name:"2018中高端_零预存时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'明星机（4G客户版）')]",name:"明星机（4G客户版）",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'明星机（4G客户版）')]",name:"明星机（4G客户版）时间",handler:"FilterChinamobileTime"} 
      text: {xpath:"//h3[contains(text(),'移动优先机型活动（高流量保底版）')]",name:"移动优先机型活动（高流量保底版）",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'移动优先机型活动（高流量保底版）')]",name:"移动优先机型活动（高流量保底版）时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'天猫感恩')]",name:"天猫感恩",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'天猫感恩')]",name:"天猫感恩时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'市场后视镜活动')]",name:"市场后视镜活动",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'市场后视镜活动')]",name:"市场后视镜活动时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'2015版带机入网合约')]",name:"2015版带机入网合约",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'2015版带机入网合约')]",name:"2015版带机入网合约时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'2016版带机入网合约')]",name:"2016版带机入网合约",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'2016版带机入网合约')]",name:"2016版带机入网合约时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'政企五福临门')]",name:"政企五福临门",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'政企五福临门')]",name:"政企五福临门时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'2017政企_和教育')]",name:"2017政企_和教育",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'2017政企_和教育')]",name:"2017政企_和教育时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'儿童腕表活动')]",name:"儿童腕表活动",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'儿童腕表活动')]",name:"儿童腕表活动时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'4G孝心机')]",name:"4G孝心机",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'4G孝心机')]",name:"4G孝心机时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'裸机购机赠话费')]",name:"裸机购机赠话费",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'裸机购机赠话费')]",name:"裸机购机赠话费时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'校园')]",name:"校园",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'校园')]",name:"校园时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'个人合约购机')]",name:"个人合约购机",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'个人合约购机')]",name:"个人合约购机时间",handler:"FilterChinamobileTime"}
      text: {xpath:"//h3[contains(text(),'飞享保底')]",name:"飞享保底",handler:"FilterChinamobile"}
      text: {xpath:"//h3[contains(text(),'飞享保底')]",name:"飞享保底时间",handler:"FilterChinamobileTime"}
      