open: {id:"show-guidechem-list",name:"盖德化工网",link:"input",timeout:15,threads:1,brower:"chrome",remark:"https://show.guidechem.com/bjjhyb/productlist7133-p1.html"}
   list: {xpath:"//li/p/a",wait:3000}
     text: {xpath:"",name:"名称"}
