open: {id:"store-coupang-detail",filter:false,image:false,name:"store.coupang详情",init:"https://www.coupang.com",link:"input",scroll:-1,major:true,brower:"chrome",timeout:20,threads:1,remark:"https://store.coupang.com/vp/vendors/C00231716/products?vendorName=Xiamen+daojing+trading+co.+LTD&productId=9800311&outboundShippingPlaceId="}
       text: {xpath:"//h2[@class='prod-buy-header__title']",name:"标题"}
       text: {xpath:"//span[@class='total-price']/strong",name:"价格"}
       text: {xpath:"//img[@class='prod-image__detail']",attribute:"data-zoom-image-url",name:"主图链接",regex:"prefix|http:"}
       text: {xpath:"",name:"颜色",handler:"CoupangColorText"}
       text: {xpath:"",name:"尺码",handler:"CoupangSizeText"}
       text: {xpath:"",name:"详情链接",handler:"CoupangDetailText"}
       text: {xpath:"",name:"商品链接",handler:"CommonCurrentUrl"}
