open: {id:"subsidesports-list-url", special:"repeatDownload",filter:false,image:true,name:"subsidesport商品链接",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"https://www.subsidesports.com/uk/team/serie-a/ac-milan?p=2"}
     list: {xpath:"//h2[@class='product-name']/a"}
       text: {xpath:"",attribute:"href",name:"链接",url:true}
