open: {id:"subsidesports-list-url-url",filter:false,image:false,name:"subsidesports队链接",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"https://www.subsidesports.com/uk/team/serie-a/ac-milan?p=2"}
     list: {xpath:"//div[@class='col-main']/div[contains(@class,'grid')]/a"}
       text: {xpath:"",attribute:"href",name:"链接",url:true}
