open: {id:"toutiao-image",filter:false,image:false,name:"今日头条图片",link:"input",urlhandler:"ToutiaoUrl",major:true,brower:"phantomjs",timeout:30,threads:1,remark:"https://m.toutiao.com/i6737980139885298187/#p=8"}
     text: {xpath:"",name:"文件夹名-标题"}
     text: {xpath:"",name:"链接",download:true}
