open: {id:"liansai500-list-main",filter:false,expire:"{date:'20190415',message:'运行异常'}",image:false,name:"500彩票链接",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"https://www.uksoccershop.com/football-boots/adidas/nitrocharge"}
   list: {xpath:"//a[text()='析']"}
       text: {xpath:"",attribute:"href",name:"500彩票析链接",regex:"replace|shuju",params:"ouzhi"}
