open: {id:"win0168-list-url",filter:false,image:true,expire:"{date:'20190415',message:'运行异常'}",name:"win0168足球",link:"input",major:true,brower:"chrome",timeout:30,threads:1,remark:"http://www.win0168.com/"}
     click: {xpath:"//a[text()='[显]']",wait:3000}
     list : {xpath:"//table[@id='table_live']/tbody/tr",include:"EuropeOdds",wait:3000,scroll:-1}
        text: {xpath:"/td[3]",name:"时间"}
        text: {xpath:"/td[13]/a[text()='欧']",attribute:"href",name:"链接",handler:"WinText",url:true,show:false}
