open: {id:"1688-product-picture2",image:false,name:"1688单品橱柜和详情页图片分文件夹",rowhandler:"AlibabaMainPicHandler",link:"input",timeout:15,threads:1,brower:"chrome-phone",remark:"1688单品的主图和详情页图片采集",urlhandler:"Open1688Sku",help:"1.批量1688商品链接\n2.采集橱柜和详情页图片.\n3.图片放到以商品名称命名的文件夹.\n4.不采集商品的信息.\n5.图片分为主图和详情图文件夹.\n6.图片顺序下载"}
   text: {xpath:"//h1[contains(@class,'d-title')]",name:"文件夹名-商品名"}
   list: {xpath:"//img[contains(@data-lazyload-src,'.jpg') or contains(@swipe-lazy-src,'.jpg')  or contains(@src,'.jpg')]",scroll:-1,moveto:"//div[contains(@class,'m-detail-price-warning')]",wait:4000}
     text: {xpath:"",name:"图片名称",filename:true,handler:"AutoCode"}
     text: {xpath:"",name:"是否主图片"}
     text: {xpath:"",name:"图片链接",handler:"M1688Picture2",download:true,show:true}
     text: {xpath:"",name:"产品链接",handler:"CommonCurrentUrl",show:false}
