open: {id:"1688company",name:"阿里巴巴店铺公司",filter:true,link:"https://m.1688.com",timeout:30,threads:1,major:true,brower:"chrome-phone",remark:"输入关键字的采集方式，1688店铺列表",urlhandler:"Open1688Url"}
  list: {xpath:"//div[@class='search-list-company']/ul/li",wait:15000,scroll:-1}
         text: {xpath:"/div/a",attribute:"href",name:"链接",show:true,url:true}