open: {id:"1688-shop-list-url",link:"queues",image:false,timeout:30,threads:2,brower:"phantomjs-phone",remark:"1688店铺商品信息图片"}
   text: {xpath:"//h1[contains(@class,'d-title')]",name:"文件夹名-商品名"}
   list: {xpath:"//img[contains(@data-lazyload-src,'.jpg') or contains(@swipe-lazy-src,'.jpg')  or contains(@src,'.jpg')]",moveto:"//div[contains(@class,'m-detail-price-warning')]",wait:10000}
     text: {xpath:"",name:"图片链接",handler:"M1688Picture",download:true,show:false}
