  open: {link:"input",id:"gongzonghao-list",name:"微信公众号链接",urlhandler:"GongzonghaoUrl",labels:"cookies",timeout:15,threads:1,major:true,brower:"phantomjs",monitor:true,remark:"http://permit.mep.gov.cn/permitExt/outside/Publicity?pageno=1&enterName=&province=&city=&treadcode=&treadname=&xkznum="}
      text: {xpath:"",name:"链接"}
      