open: {id:"jd-die-http-shop-url",labels:"关键词",urlhandler:"JdHttpUrl",name:"京东店铺请求链接采集",link:"input",timeout:30,threads:1,major:true,brower:"phantomjs",help:"京东搜索关键词后，采集列表分页的所有商品链接"}
    text: {xpath:"",name:"链接"}
    text: {xpath:"",name:"店铺"}
